# Example config file for pretty-ts-imports
#
# This one mostly uses the default import settings but also includes an example
# for custom compare functions.
sortImports:
  # These are the compare functions used to sort the imports.
  #
  # Primp runs through this list until it finds a compare function that
  # doesn't return 0, therefore the order is important.
  # To always have the same expected result, at least the last function
  # should possible never return 0.
  - packagesFirst
  - comparePaths
  - flatPathsFirst
  - namespacesBeforeNamed
  - defaultTypesFirst
  - dotJSFirst
  - compareSources
# - deepPathsFirst
# - defaultsCompareTypes
# - relativesFirst
sortImportElement:
  # These are the compare functions use to sort each imported element
  # inside an import statement.
  # Because of TS limitations only named imports (the ones inside the
  # brackets) can be sorted.
  #
  # Same as the sortImports, primp runs through every one trying to find a
  # non 0 returning function.
  - typesBeforeObjects
  - compareTypes
  - compareElements
separateBy:
  # These are the categories to group by.
  #
  # Primp uses these category functions to determine where to put empty lines
  # as separation.
  - types
formatting:
  # This is the setting to format the imports.
  indent: 2 # Spaces used to indent if max columns is exceeded.
  bracketIndent: 0 # Spaces used at the start and end of import brackets.
  quoteStyle: double # How the "from" should be quoted.
  maxColumns: 80 # The maximum column width, primp tries to not exceed this
require:
  # If you need more compare functions than provided you can require them
  # here.
  # Firstly name the key how you want it to be used and secondly set the
  # value to the function path relative to this file.
  # This example puts packages that end with ".js" before others.
  dotJSFirst: ../sort_rules/imports/dotJSFirst.ts
